---
- name: install zabbix repository
  yum: name=http://repo.zabbix.com/zabbix/2.4/rhel/6/x86_64/zabbix-release-2.4-1.el6.noarch.rpm state=installed

- name: be sure dependencies for selinux configuration are installed
  yum: name={{ item }} state=installed
  with_items:
    - libselinux-python
 
- name: install zabbix-server
  yum: name={{ item }} state=installed enablerepo=zabbix,zabbix-non-supported
  with_items:
    - MySQL-python
    - zabbix-web-mysql
    - zabbix-web-japanese
    - zabbix-agent

- name: diable zabbix repo
  replace: dest=/etc/yum.repos.d/zabbix.repo regexp='enabled=1' replace='enabled=0'  backup=yes

- name: configure php.ini
  lineinfile: dest=/etc/php.ini insertafter=';date\.timezone.*' line='date.timezone=Asia/Tokyo' state=present backup=yes

- name: set enforce disable with SELinux
  selinux: state=disabled

- name: configure iptables(firewall)
  iptables: chain=INPUT ctstate=NEW protocol=tcp match=tcp destination_port={{ item }} jump=ACCEPT
  with_items:
    - 80
    - 443
  register: iptables_config

- name: remove reject rule from iptables
  iptables: state=absent chain=input reject_with=icmp-host-prohibited
  register: iptables_reject_rule
  when: iptables_config.changed

- name: add reject rule from iptables
  iptables: state=present chain=input reject_with=icmp-host-prohibited
  when: iptables_reject_rule.changed

- name: save iptables config
  command: service iptables save
  when: iptables_config.changed

- name: start http server
  service: name=httpd state=started enabled=yes
