---
- name: install zabbix repository
  yum: name=http://repo.zabbix.com/zabbix/2.4/rhel/6/x86_64/zabbix-release-2.4-1.el6.noarch.rpm state=installed

- name: be sure dependencies for selinux configuration are installed
  yum: name={{ item }} state=installed
  with_items:
    - libselinux-python
 
- name: install zabbix-server
  yum: name={{ item }} state=installed enablerepo=zabbix,zabbix-non-supported
  with_items:
    - MySQL-python
    - zabbix-web-mysql
    - zabbix-web-japanese
    - zabbix-agent

- name: diable zabbix repo
  replace: dest=/etc/yum.repos.d/zabbix.repo regexp='enabled=1' replace='enabled=0'  backup=yes

- name: configure php.ini
  lineinfile: dest=/etc/php.ini insertafter=';date\.timezone.*' line='date.timezone=Asia/Tokyo' state=present backup=yes

- name: set enforce disable with SELinux
  selinux: state=disabled

- name: check iptables setting
  shell: iptables -L | grep -q web-server
  register: register_webServer
  failed_when: register_webServer.rc not in [0, 1]
  changed_when: false

- name: configure iptables(firewall)
  shell: iptables -I INPUT -p tcp -m state --state NEW -m tcp --dport {{ item }} -j ACCEPT -m comment --comment "for web-server"
  register: iptables_config
  with_items:
    - 80
    - 443
  when: register_webServer.rc == 1

- name: save iptables config
  command: service iptables save
  when: iptables_config.changed

- name: start http server
  service: name=httpd state=started enabled=yes
