---
- name: confirm installed mysql staff
  yum: name={{ item }} state=present
  with_items:
    - MySQL-python
    - mysql-server

- name: start mysqld
  service: name=mysqld state=started enabled=yes

- name: build database for zabbix
  mysql_db: name=zabbix encoding=utf8 state=present

- name: create mysql user for zabbix
  mysql_user: name=zabbix password=zabbix priv=zabbix.*:ALL,GRANT state=present

- name: check iptables setting
  shell: iptables -L | grep -q mysql
  register: register_mysql
  failed_when: register_mysql.rc not in [0, 1]
  changed_when: false

- name: configure iptables(firewall)
  shell: iptables -I INPUT -p tcp -m state --state NEW -m tcp --dport {{ item }} -j ACCEPT -m comment --comment "mysql"
  register: iptables_config
  with_items:
    - 3306
  when: register_mysql.rc == 1

- name: save iptables config
  command: service iptables save
  when: iptables_config.changed
