- hosts: zabbix-server
  vars:
  handlers:
    - name: restart httpd
      service: name=httpd state=restarted enabled=yes

    - name: restart network service
      service: name=network state=restarted enables=yes

  become: yes
  become_method: su
  tasks:
    - name: be sure gcc-c++ is installed
      yum: name=gcc-c++ state=installed

    - name: be sure python devel is installed
      yum: name=python-devel state=installed

    - name: install telnet client
      yum: name=telnet state=installed

    - name: install libjpeg-devel
      yum: name=libjpeg-turbo-devel state=installed

    - name: install epel repository
      yum : name=epel-release state=installed
 
    - name: install docker-io
      yum: name=docker-io state=installed

    - name: install snmptt
      yum : name=snmptt state=installed

    - name: install zabbix repository
      yum: name=http://repo.zabbix.com/zabbix/2.4/rhel/6/x86_64/zabbix-release-2.4-1.el6.noarch.rpm state=installed

    - name: install zabbix-server
      yum: name=zabbix-server-mysql,zabbix-web-mysql,zabbix-web-japanese,zabbix-agent state=installed enablerepo=zabbix,zabbix-non-supported disablerepo=epel

    - name: start mysqld
      service: name=mysqld state=started enabled=yes

    - name: build database for zabbix
      mysql_db: name=zabbix encoding=utf8 state=present

    - name: create mysql user for zabbix
      mysql_user: name=zabbix password=zabbix priv=zabbix.*:ALL,GRANT state=present

    - name: create schema in zabbix database
      script: createZabbixSchema.sh creates=/home/ansible/createZabbixSchemaDone

    - name: copy a iptables setting file to the host
      copy: backup=yes src=iptables dest=/etc/sysconfig/iptables

    - name: copy a ntp.conf setting file to the host
      copy: backup=yes src=ntp.conf dest=/etc/ntp.conf

    - name: copy a php.ini setting file to the host
      copy: backup=yes src=php.ini dest=/etc/php.ini

    - name: copy a zabbix_agent setting file to the host
      copy: backup=yes src=zabbix_agentd.conf dest=/etc/zabbix/zabbix_agentd.conf

    - name: copy a zabbix_server setting file to the host
      copy: backup=yes src=zabbix_server.conf dest=/etc/zabbix/zabbix_server.conf

    - name: set enforce disable with SELinux
      selinux: state=disabled

    - name: starts zabbix-server
      service: name=zabbix-server state=started enabled=yes
      notify: restart httpd
