---
- name: install zabbix repository
  yum: name=http://repo.zabbix.com/zabbix/2.4/rhel/6/x86_64/zabbix-release-2.4-1.el6.noarch.rpm state=installed

- name: diable zabbix repo
  replace: dest=/etc/yum.repos.d/zabbix.repo regexp='enabled=1' replace='enabled=0'  backup=yes

- name: install zabbix-server
  yum: name={{ item }} state=installed enablerepo=zabbix,zabbix-non-supported
  with_items:
    - zabbix-server-mysql

- name: set db password for zabbix-server
  lineinfile: dest=/etc/zabbix/zabbix_server.conf insertafter='# DBPassword=' line='DBPassword=zabbix' state=present backup=yes

- name: find sql directory for zabbix
  find: patterns='zabbix-server-mysql-2.4.*' paths='/usr/share/doc/' file_type=directory
  register: sql_dir 

- name: create tables of zabbix
  mysql_db: name=zabbix login_user=zabbix login_password=zabbix state=import target={{ sql_dir.files[0].path }}/create/{{ item }}
  with_items:
    - schema.sql
    - images.sql
    - data.sql
  ignore_errors: True

- name: configure iptables(firewall)
  iptables: chain=INPUT ctstate=NEW protocol=tcp match=tcp destination_port={{ item }} jump=ACCEPT
  with_items:
    - 161
    - 162
    - 10051
  register: iptables_config

- name: remove reject rule from iptables
  iptables: state=absent chain=input reject_with=icmp-host-prohibited
  register: iptables_reject_rule
  when: iptables_config.changed

- name: add reject rule from iptables
  iptables: state=present chain=input reject_with=icmp-host-prohibited
  when: iptables_reject_rule.changed

- name: save iptables config
  command: service iptables save
  when: iptables_config.changed

- name: start zabbix-server
  service: name=zabbix-server state=started enabled=yes
