- name: be sure Python3.4.3 is not installed
  command: ls -l /opt/bin/python3.4
  ignore_errors: True
  register: ck_python3

- name: be sure dependencies are installed
  yum: name={{ item }} state=installed
  with_items:
    - gcc-c++
    - python-devel 
    - libjpeg-turbo-devel
    - libxml2
    - libxslt
    - git

- name: set python3.4.3 source file to the remote machine
  unarchive: src=Python-3.4.3.tar.xz dest=/root copy=yes
  when: ck_python3|failed

- name: configure, make, make alt install python3.4.3
  command: ./configure --prefix=/opt chdir=/root/Python-3.4.3 creates=/opt/bin/python3.4

- command: make chdir=/root/Python-3.4.3 creates=/opt/bin/python3.4

- command: make altinstall chdir=/root/Python-3.4.3 creates=/opt/bin/python3.4

- name: ensure pip is installed
  command: /opt/bin/python3.4 -m ensurepip

- name: make symboliclink of python3 and pip3 command in /usr/bin
  file: path=/usr/bin/{{ item }} state=link src=/opt/bin/{{ item }}.4
  with_items:
    - python3
    - pip3

- name: install python packages on which report server depends
  pip: executable=pip3 name={{ item }} state=latest
  with_items:
    - pip
    - ipython
    - numpy
    - pandas
    - datetime
    - python-dateutil
    - bottle
    - wtforms
    - pillow
    - openpyxl
    - python-docx
    - python-pptx
    - pyzabbix

- name: git clone report server python codes
  command: git clone https://github.com/HodakaShigemi/zabbix_api chdir=/opt creates=/opt/zabbix_api

- name: make symbolic links of python codes
  file: path=/nttme/{{ item }} state=link src=/opt/{{ item }}
  with_items:
    - ansible
    - ReportServer

- name: configure iptables(firewall)
  iptables: chain=INPUT ctstate=NEW protocol=tcp match=tcp destination_port={{ item }} jump=ACCEPT
  with_items:
    - 8080
