---
- name: install zabbix repository
  yum: name=http://repo.zabbix.com/zabbix/2.4/rhel/6/x86_64/zabbix-release-2.4-1.el6.noarch.rpm state=installed

- name: install zabbix-server
  yum: name={{ item }} state=installed enablerepo=zabbix,zabbix-non-supported
  with_items:
    - zabbix-server-mysql
    - zabbix-web-mysql
    - zabbix-web-japanese
    - zabbix-agent

- name: diable zabbix repo
  replace: dest=/etc/yum.repos.d/zabbix.repo regexp='enabled=1' replace='enabled=0'  backup=yes

-name: create tables of zabbix
 mysql_db: login_host={{ dbserver }} name=zabbix login_user=zabbix login_password=zabbix import=/usr/share/doc/zabbix-server-mysql-2.4.*/create/{{ item }}
 with_items:
   - schema.sql
   - images.sql
   - data.sql

- name: configure php.ini
  lineinfile: dest/etc/php.ini insertafter=';date\.timezone.*' line='date.timezone = Asia/Tokyo' state=present backup=yes

- name: set enforce disable with SELinux
  selinux: state=disabled

- name: configure iptables(firewall)
  iptables: chain=INPUT ctstate=NEW protocol=tcp match=tcp destination_port={{ item }} jump=ACCEPT
  with_items:
    - 80
    - 443
