- hosts: zabbix-server
  vars:
  handlers:
    - name: restart httpd
      service: name=httpd state=restarted enabled=yes

    - name: restart network service
      service: name=network state=restarted enables=yes

  become: yes
  become_method: su
  tasks:
    - name: be sure gcc-c++ is installed
      yum: name=gcc-c++ state=installed

    - name: be sure python devel is installed
      yum: name=python-devel state=installed

    - name: install docker-io
      yum: name=docker-io state=installed

    - name: install libjpeg-devel
      yum: name=libjpeg-turbo-devel state=installed

    - name: install telnet
      yum: name=telnet state=installed

    - name: install docker
      yum: name=docker-io state=installed

    - name: install jpeg library
      yum: name=libjpeg-turbo-devel state=installed

    - name: be sure python-setuptools is installed
      yum: name=python-setuptools state=installed

    - name: install pip
      easy_install: name=pip

    - name: install epel repository
      yum : name=epel-release state=installed

    - name: install snmptt
      yum : name=snmptt state=installed

     - name: install docker linux countainer package
      yum: name=zabbix-server-mysql,zabbix-web-mysql,zabbix-web-japanese,zabbix-agent state=installed enablerepo=zabbix,zabbix-non-supported disablerepo=epel

   - name: install zabbix repository
      yum: name=http://repo.zabbix.com/zabbix/2.4/rhel/6/x86_64/zabbix-release-2.4-1.el6.noarch.rpm state=installed

    - name: install zabbix-server
      yum: name=zabbix-server-mysql,zabbix-web-mysql,zabbix-web-japanese,zabbix-agent state=installed enablerepo=zabbix,zabbix-non-supported

    - name: start mysqld
      service: name=mysqld state=started enabled=yes

    - name: build database for zabbix
      mysql_db: name=zabbix encoding=utf8 state=present

    - name: create mysql user for zabbix
      mysql_user: name=zabbix password=zabbix priv=zabbix.*:ALL,GRANT state=present

    - name: create schema in zabbix database
      shell: /usr/bin/mysql -uroot zabbix < /usr/share/doc/zabbix-server-mysql-2.4.?/create/schema.sql creates=/var/lib/mysql/zabbix/users.frm

    - name: create images in zabbix database
      shell: /usr/bin/mysql -uroot zabbix < /usr/share/doc/zabbix-server-mysql-2.4.?/create/images.sql
      ignore_errors: yes

    - name: create data in zabbix database
      shell: /usr/bin/mysql -uroot zabbix < /usr/share/doc/zabbix-server-mysql-2.4.?/create/data.sql
      ignore_errors: yes

    - name: update numpy
      pip: name=numpy state=latest

    - name: install pandas python module
      pip: name=pandas state=present

    - name: besure datetime module is installed
      pip: name=datetime state=present

    - name: install bottle web framework python module
      pip: name=bottle state=present

   - name: install wtforms http-form python module
      pip: name=wtforms state=present

    - name: install pillows. An image utility module of python
      pip: name=pillow state=present

    - name: install openpyxl. An python module for Microsoft Excel file.
      pip: name=openpyxl state=present

    - name: set enforce disable with SELinux
      selinux: state=disabled

    - name: starts zabbix-server
      service: name=zabbix-server state=started enabled=yes
      notify: restart httpd

    - name: allow http connection from network
      iptables: chain=INPUT protocol=tcp destination_port=http jump=ACCEPT

    - name: allow snmp response from network
      iptables: chan=INPUT protocol=udp destination_port=161 jump=ACCEPT

    - name: allow snmp trap from network
      iptables: chan=INPUT protocol=udp destination_port=162 jump=ACCEPT

    - name: allow ftp connection from network
      iptables: chain=INPUT protocol=tcp destination_port=ftp jump=ACCEPT

    - name: allow tftp connection from network
      iptables: chain=INPUT protocol=udp destination_port=tftp jump=ACCEPT
