---
- name: install zabbix repository
  yum: name=http://repo.zabbix.com/zabbix/2.4/rhel/6/x86_64/zabbix-release-2.4-1.el6.noarch.rpm state=installed

- name: diable zabbix repo
  replace: dest=/etc/yum.repos.d/zabbix.repo regexp='enabled=1' replace='enabled=0'  backup=yes

- name: install zabbix-agent
  yum: name={{ item }} state=installed enablerepo=zabbix,zabbix-non-supported
  with_items:
    - zabbix-agent

- name: check iptables setting
  shell: iptables -L | grep -q zabbix-agent
  register: register_zabbixAgent
  failed_when: register_zabbixAgent.rc not in [0, 1]
  changed_when: false

- name: configure iptables(firewall)
  shell: iptables -I INPUT -p tcp -m state --state NEW -m tcp --dport {{ item }} -j ACCEPT -m comment --comment "zabbix-agent"
  register: iptables_config
  with_items:
    - 10050
  when: register_zabbixAgent.rc == 1

- name: save iptables config
  command: service iptables save
  when: iptables_config.changed

- name: start zabbix-agent
  service: name=zabbix-agent state=started enabled=yes
