---
- name: install zabbix repository
  yum: name=http://repo.zabbix.com/zabbix/2.4/rhel/6/x86_64/zabbix-release-2.4-1.el6.noarch.rpm state=installed

- name: diable zabbix repo
  replace: dest=/etc/yum.repos.d/zabbix.repo regexp='enabled=1' replace='enabled=0'  backup=yes

- name: install zabbix-server
  yum: name={{ item }} state=installed enablerepo=zabbix,zabbix-non-supported
  with_items:
    - zabbix-agent

- name: configure iptables(firewall)
  iptables: chain=input ctstate=new protocol=tcp match=tcp destination_port={{ item }} jump=accept
  with_items:
    - 10050
  register: iptables_config

- name: remove reject rule from iptables
  iptables: state=absent chain=input reject_with=icmp-host-prohibited
  register: iptables_reject_rule
  when: iptabls_config.changed

- name: add reject rule from iptables
  iptables: state=present chain=input reject_with=icmp-host-prohibited
  when: iptables_reject_rule.changed

- name: save iptables config
  command: service iptables save
  when: iptables_config.changed
